### GET request to get all patients
GET http://localhost:4000/patients

### POST request to create a patient
POST http://localhost:4000/patients
Content-Type: application/json

{
    "name":"Robbie Weeks",
    "email":"xlstc123@gmail.com",
    "address":"123 smith road",
    "dateOfBirth":"1995-03-05",
    "registeredDate":"2026-03-05"
}