### GET request to get all patients
GET http://localhost:4000/patients

### POST request to create a patient
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Robbie Weeks with Billing Account 2333",
  "email": "xlstctesting@gmail.com",
  "address": "123 smith road",
  "dateOfBirth": "1995-03-05",
  "registeredDate": "2026-03-05"
}

### PUT request to update a patient info
PUT http://localhost:4000/patients/223e4567-e89b-12d3-a456-426614174014
Content-Type: application/json

{
  "name": "Robbie Knu Weeks",
  "email": "xlstc1234@gmail.com",
  "address": "123 smith road",
  "dateOfBirth": "1995-03-05",
  "registeredDate": "2026-03-05"
}